# -*- coding: utf-8 -*-
"""proyecto_MRDE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ldrLSU3sCwkC_wK3yfvx8vPg9thSXHE

#**Modelo de recomendación de dispositivos neuroendovasculares basado en características técnicas.**

El presente Trabajo de Fin de Máster tiene como objetivo desarrollar un sistema inteligente de recomendación de dispositivos neuroendovasculares, entrenado a partir de una base de datos técnica propia del servicio de neurorradiología del INCA, esta base fue realizada a travez de sus provedores mas comunmente utilizados en nuestros servicio de Neuroradiologia Intervencional. Este sistema será capaz de sugerir alternativas compatibles en tiempo real ante la no disponibilidad de un dispositivo específico, utilizando métricas de similitud entre variables clave como el diámetro interno, diámetro externo y longitud del catéter etc.

*La implementación de esta herramienta busca aportar un valor clínico tangible, demostrando que incluso con una base de datos estructurada pero acotada —sin necesidad de historiales clínicos extensos— es posible construir soluciones de IA aplicadas a problemas reales en el entorno hospitalario. Asimismo, se plantea como un modelo replicable y escalable a otros servicios clínicos y centros hospitalarios que enfrentan desafíos similares*.

#Justificación del Proyecto

En pabellones de alta complejidad donde se realizan procedimientos endovasculares, la selección del dispositivo correcto impacta directamente en la seguridad, eficacia y costos del procedimiento. La gran variedad de microcatéteres y dispositivos neurovasculares existentes, sumado a la variabilidad en la experiencia de los profesionales, vuelve crítica la sistematización del conocimiento técnico.

*Este proyecto se justifica por la necesidad de estandarizar esa decisión y optimizar el proceso de selección mediante una solución tecnológica robusta, integrable con sistemas clínicos y validada en entornos reales de uso*.

##Objetivo General
El presente Trabajo de Fin de Máster tiene como objetivo el diseño e implementar un modelo predictivo basada en inteligencia artificial que recomiende dispositivos neuroendovasculares alternativos en procedimientos intervencionales, utilizando criterios de compatibilidad técnica. Esta herramienta busca apoyar la toma de decisiones clínicas en tiempo real ante la no disponibilidad de ciertos insumos en el servicio de neurorradiología del Instituto de Neurocirugía de Chile, optimizando la selección de catéteres, microcatéteres y guías según sus propiedades físicas y funcionales.
###Objetivos Específicos

•	*Se desarrollo una base de datos técnica de dispositivos basada en especificaciones comparables*.

•	*Preprocesar y normalizar los datos clínicamente relevantes*.

•	*Implementar una función de recomendación basada en distancia euclidiana*.

•	*Validar la precisión del modelo según bibliografia y bases tecnicas de provedores, ejemplos como el Rebar-18 y viceversa con el Vasco+18 u otros dispositivos*.

•	*Explorar su integración futura con aplicaciones móviles como Smart Device*.

#Marco Teórico
La inteligencia artificial aplicada al entorno clínico ha crecido de forma exponencial, especialmente en áreas donde se requiere apoyo a la toma de decisiones. Modelos de recomendación por similitud técnica o perfiles vectorizados han demostrado ser útiles en campos como farmacología, dispositivos ortopédicos y recientemente, neurointervención.

*En este contexto, el uso de técnicas como MinMaxScaler para normalización y la métrica de distancia Euclidiana permiten comparar dispositivos en un espacio de características técnicas con una base matemática sólida y explicable*.

# Estado del Arte
Según la revisión realizada en el artículo “Advancing Embodied Intelligence in Robotic-Assisted Endovascular Procedures: A Systematic Review of AI Solutions”, se observa que la mayoría de las aplicaciones actuales se enfocan en la asistencia robótica o planificación vascular basada en imágenes.
Sin embargo, existen pocas herramientas diseñadas exclusivamente para recomendar dispositivos con base en sus dimensiones técnicas como ID (inner diameter), OD (outer diameter), longitud, o compatibilidad química (DMSO), entre otras.

*Por ello, nuestro enfoque se sitúa como una innovación específica para la elección de catéteres según sus dimensiones en el ámbito de la imagenología intervencionista*.

#Metodología y desarrollo técnico

**Construcción de la base de datos**

El primer paso consistió en la sistematización de una propia base de datos estructurada y con información técnica de los dispositivos disponibles en el servicio a traves de las fichas tecnicas que nos proporcionaron nuestros provedores, y a travez de la recoleccion de los datos tecnicos que proporcionan los embases de estos dispositivos que se encuentran en nuestro servicio, en gran mayoria los dispositivos que utilizamos en el servicio de neuroradiologia intervencional son licitados anualmente a traves del area encaragada de compras y abastecimiento de nuestro hospital.

La base se estructuró con catéteres guía, microcatéteres e intermedios, e incluyó variables técnicas esenciales tales como:

•	*Diámetro externo (OD) en milímetros, pulgadas y French (Fr)*

•	*Diámetro interno (ID) en milímetros, pulgadas y  French*

•	*Longitud del dispositivo (en cm)*

•	*Marca comercial y tipo de dispositivo*

•	*Y DMSO compatible (para desarrollo futuro)*

#Lógica del sistema de recomendación

##Este principio parte de la siguiente idea clínica y lógica:

**¿Qué es el principio de similitud técnica?**

 “Si dos dispositivos neuroendovasculares tienen características técnicas o valores muy parecidas en variables claves (por ejemplo, diámetro interno, diametro externo, longitud y French similares), es probable que puedan usarse como alternativas o complementos en el mismo tipo de procedimiento.” Y considerarse compatibles.

"*Dispositivos neuroendovasculares que comparten características técnicas similares son más compatibles entre sí para determinados usos clínicos*."

Para cuantificar esa similitud, empleamos una métrica matemática muy conocida en machine learning: llamada distancia Euclídea, entre las variables técnicas de los dispositivos, previa normalización.

**¿Qué es la distancia euclídea?**

Es una fórmula matematica que mide la distancia "recta" entre dos puntos en un espacio multidimensional. En tu caso, cada dispositivo es un punto en un espacio definido por las variables técnicas: diámetro externo (OD), diámetro interno (ID), longitud, medida en French (Fr), etc.

📐 Fórmula matemática:

Para dos dispositivos con variables (x1,x2,x3)(x1,x2,x3) e (y1,y2,y3)(y1,y2,y3), la distancia euclídea d es;

•	d=√(x1−y1)2+(x2−y2)2+(x3−y3)2

**¿Cómo ayuda la distancia euclídea?**

La distancia euclídea te da una forma cuantitativa de medir la similitud. Mientras menor sea la distancia entre dos dispositivos, más similares son sus valores técnicos.

Interpretación;

•	*Valores más bajos de distancia = dispositivos más similares.*

•	*Si la distancia es cero, los dispositivos son idénticos en las variables analizadas.*

•	*Tu sistema permite, dado un dispositivo clínico conocido (como Rebar-18), recomendar otros con características técnicas cercanas, ayudando en la elección de materiales alternativos para procedimientos neuroendovasculares.*

####Esta lógica fue implementada usando scikit-learn y numpy, con un enfoque centrado en compatibilidad estructural (lumen, diámetro, longitud), sin requerir aún, datos clínicos o anatómicos del paciente.

¿Por qué esto es útil?

Tu sistema necesita diferenciar entre pares de dispositivos técnicamente compatibles y no compatibles, sin intervención humana.

•	*El cálculo de la distancia euclídea automatiza esa evaluación.*

•	*Permite ordenar y recomendar los dispositivos más cercanos al de referencia (por ejemplo, Rebar-18) de forma rápida y objetiva.*

•	*Esto optimiza la selección de dispositivos alternativos en pabellones donde la disponibilidad puede cambiar.*

##Implementación de la aplicación

Para facilitar el uso clínico, se desarrolló un modelo utilizando Google Colab, permitiendo:

•	Ingreso de un dispositivo que se encuentra no disponible.

•	Visualización de hasta 3 dispositivos alternativos o los primeros tres más similares en orden creciente o por semaforo de color (verde= Alta similitud tecnica; amarillo=Mediana similitud tecnica ; rojo=Baja similitu tecnica).

•	Presentación ordenada de los resultados según distancia de similitud Euclediana.

La aplicación puede ejecutarse localmente o desplegarse online mediante servicios como Google Colab, y se plantea como un módulo que en el futuro podría integrarse con sistemas clínicos como TrakCare, SAP o APP.

##Exploración y Preprocesamiento de Datos

#Se cargó la base de datos base_dispositivos_normalizada, compuesta por campos como:

•	*nombre*

•	*id_mm, od_mm, id_fr, od_fr, id_pulgadas, od_pulgadas*

•	*longitud_cm (con valores tipo "150/160" convertidos a 150)*

•	*dmso_compatible*


#Se aplicaron los siguientes pasos:

•	*Normalización de nombres de columnas.*

•	*Conversión de strings con coma a float (0,028 → 0.028).*

•	*Imputación o eliminación de valores nulos (solo si existen valores nulos)*

•	*Conversión de longitudes con múltiplos separados por "/" al primer valor.*

¿Por qué normalizamos antes?

Las variables como "Longitud" (que puede ser 130 o 170) tienen escalas mayores como (cm) que otras como "OD_mm" (0.91, por ejemplo). Eso puede afectar el cálculo de distancia. Y a la vez estan separados por "/" que tambien hay que normalizar.

###*Por eso normalizaremoss los datos con MinMaxScaler en nuestro colab, para que todas las variables estén entre 0 y 1 y todas contribuyan de forma justa al cálculo de similitud.*

#Paso 1. Importar y configurar librerías clave:

Numpy, pandas, matplotlib y otras herramientas como scikit-learn que son esenciales para el análisis de datos y construcción del modelo predictor. Al cargar todas estas bibliotecas que son necesarias para: limpieza, visualización, modelado, imputación de datos faltantes (si es que los hay) y enriquecimiento de impresión en consola (gracias a rich).

El uso de rich para visualizar información en consola es una excelente adición para la claridad del flujo de trabajo.

Asegura que se puedan ver todas las columnas y hasta 50 filas al trabajar en Google Colab.
"""

# Usaremos rich para enriquecer la impresion por pantalla
#Importamo libreria de trabajo de cualquier proyecto de aprendizaje automatico
import numpy as np #Esta biblioteca es fundamental para las operaciones numéricas en Python, especialmente al trabajar con matrices y arreglos. Proporciona herramientas eficientes para cálculos matemáticos.
import seaborn as sns # se utiliza para crear gráficos estadísticos atractivos e informativos. Simplifica la generación de visualizaciones complejas.
import pandas as pd # es esencial para trabajar con datos estructurados, como tablas y hojas de cálculo.
import numpy as np # fundamental para las operaciones numéricas en Python, especialmente para trabajar con matrices.
import matplotlib.pyplot as plt # biblioteca ampliamente utilizada para crear visualizaciones estáticas, interactivas y animadas en Python.

from rich import print # Esta biblioteca se utiliza para añadir texto enriquecido y un formato atractivo a la salida de la terminal.
from rich.console import Console #Esta clase se utiliza para crear un objeto de consola para un control avanzado sobre la salida de la terminal.
from rich.panel import Panel #Esta clase se utiliza para crear paneles con bordes alrededor de la salida de la terminal
from rich.syntax import Syntax #Esta clase se utiliza para resaltar código de sintaxis en la terminal.

# Librerías de Scikit-learn
from sklearn.impute import SimpleImputer # Para imputación de valores faltantes
from sklearn.preprocessing import LabelEncoder # Para codificación de variables categóticas
from sklearn.preprocessing import StandardScaler # Para aplicar transformación de valores
from statsmodels.tools import add_constant  # Para agregar una columna de unos (constante) al conjunto de datos
import statsmodels.api as sm  # Para construir un modelo de regresión logística para selección de variables
from scipy import stats  # Para realizar cálculos estadísticos
from sklearn.linear_model import LogisticRegression # Modelo de regresión logística para ajustar los datos
from sklearn.metrics import accuracy_score, classification_report, roc_curve, roc_auc_score # Métricas de evaluación del modelo
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt # Librería para gráficas

from rich.console import Console  # Esto importa la clase Console
console = Console()              # Esto crea una instancia llamada console

# Configuracion para mostrar mas columnas y filas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

"""#Paso 2. Carga y exploración de los datos:

Este bloque de código es el punto de partida del modelo predictivo, ya que carga la base de datos con las características técnicas de los dispositivos neuroendovasculares que serán utilizados para hacer recomendaciones basadas en similitud.

Una vez cargado, el archivo se transformó en un DataFrame de pandas que permitira la posterior limpieza, normalización y análisis de similitud entre los dispositivos.
"""



from google.colab import files

# Solicitar al usuario que cargue un archivo
console.print("Por favor, selecciona un archivo CSV para cargar.")
uploaded = files.upload()

# El archivo cargado se almacena en un diccionario
# Obtenemos el nombre del primer (y unico) archivo cargado
file_name = list(uploaded.keys())[0]

console.print(f"[bold]Archivo cargado:[/bold] {file_name}")

df = pd.read_csv(file_name, encoding='utf-8-sig')

"""Se cargó una base de datos estructurada en formato .csv que contiene las características técnicas de dispositivos neuroendovasculares (diámetro interno, externo, longitud, compatibilidad DMSO, entre otros). El archivo fue cargado utilizando la función files.upload() desde Google Colab.

Una vez cargado, se utilizó la librería pandas para leer el archivo con pd.read_csv() y se almacenó como un DataFrame.

Se inspeccionaron las primeras filas utilizando df.head(), lo cual permitió confirmar la correcta lectura del archivo y visualizar columnas clave como nombre, id_mm, od_mm, longitud_cm, id_fr, od_fr, id_pulgadas, od_pulgadas y dmso_compatible.


"""

# Importamos pandas para manejo de datos y files para cargar archivos
import pandas as pd
from google.colab import files

#Cargar archivo CSV desde tu computador
uploaded = files.upload()

# Obtener el nombre del archivo cargado
file_name = list(uploaded.keys())[0]

# Leer el archivo CSV y almacenarlo en un DataFrame llamado df
df = pd.read_csv(file_name, encoding='utf-8-sig')
df.head()  # Mostrar las primeras filas para inspección visual

"""#Paso 3. Exploración y Preprocesamiento de Datos

Algunas columnas como 'ï»¿nombre' deben ser renombradas: Se eliminó cualquier carácter especial o codificación errónea, como el símbolo 'í' presente en algunos nombres de columnas. Esto previene errores al acceder a columnas por nombre en las etapas posteriores del análisis.

Verificación de valores nulos: Se comprobó si existían celdas vacías en las columnas del dataset, obteniendo como resultado cero valores faltantes, lo cual permite continuar sin aplicar imputación.

Normalización de la columna longitud_cm: Algunas celdas contenían múltiples valores separados por '/', como por ejemplo “150/160”. Para efectos del modelo, se extrajo solamente el primer valor numérico como una representación estándar de la longitud del dispositivo. Este valor se convirtió a tipo float para permitir su análisis numérico.
"""

# Corregir nombre de columna si aparece con errores de codificación
df.columns = [col.strip().lower().replace('ï»¿', '') for col in df.columns]
print(df.columns) # Verificamos que los nombres estén correctos

# Corregir nombre de columna si aparece con errores de codificación
df.columns = [col.strip().lower().replace('ï»¿', '') for col in df.columns]
print(df.columns)

print(df.columns)

columnas_tecnicas = ['id_mm', 'od_pulgadas', 'od_mm', 'od_fr',
                     'id_pulgadas', 'id_fr', 'longitud_cm']

# Verificación (opcional) de valores faltantes
print("¿Hay valores nulos?")
print(df.isna().sum()) # Resultado debe ser 0 para todas las columnas

# 📏 Extraer primera longitud si hay múltiples valores separados por '/'
df['longitud_cm'] = df['longitud_cm'].astype(str).str.split('/').str[0].astype(float)

"""El dataset ahora tiene:

Nombres limpios y en minúscula como id_mm, od_mm, longitud_cm.

Todas las celdas completas (sin nulos).

La columna longitud_cm lista para ser procesada como número decimal.
"""

# Corregir separadores decimales con comas en todas las columnas técnicas
columnas_tecnicas = ['id_mm', 'od_pulgadas', 'od_mm', 'od_fr',
                     'id_pulgadas', 'id_fr', 'longitud_cm']

# Reemplazar comas por puntos y convertir a float
for col in columnas_tecnicas:
    df[col] = df[col].astype(str).str.replace(',', '.').astype(float)

"""#Paso 4. Normalización con MinMaxScaler

Se normalizaron las columnas técnicas (diámetros, longitud) para que todas estén en la misma escala de 0 a 1.

Algunos valores (como Longitud_cm = 150) tienen escalas muy distintas a OD_mm = 0.8, por ejemplo.

Si no normalizas, las variables con números más grandes dominarán el cálculo de distancias, falseando la similitud técnica.

MinMaxScaler permite que todas las variables aporten por igual a la distancia entre dispositivos. Y me Define X antes de usarlo.
"""

# Escalar con MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Instanciar el normalizador
scaler = MinMaxScaler()

# Aplicar la transformación a las columnas técnicas
x = scaler.fit_transform(df[columnas_tecnicas])

# Crear nuevo DataFrame con los datos normalizados
df_normalizado = pd.DataFrame(x, columns=columnas_tecnicas)

# Agregar columna 'nombre' para identificar los dispositivos
df_normalizado['nombre'] = df['nombre']

# Verificar que no haya valores nulos tras la transformación
print(df_normalizado.isna().sum())

df_normalizado = df_normalizado.fillna(df_normalizado.mean(numeric_only=True))

from sklearn.metrics.pairwise import euclidean_distances

def recomendar_dispositivos_coloreado(nombre_dispositivo, df, columnas_tecnicas, top_n=5, considerar_dmso=None, considerar_segunda_longitud=False):
    nombre_dispositivo = nombre_dispositivo.lower()
    df_temp = df.copy()

    # Filtro por DMSO si se solicita
    if considerar_dmso is not None:
        df_temp = df_temp[df_temp['dmso_compatible'] == int(considerar_dmso)]

    # Filtro por segunda longitud (en caso de rangos tipo "115/125/132")
    if considerar_segunda_longitud:
        df_temp = df_temp[df_temp['longitud_cm'].astype(str).str.contains('/')]

    # Extraer datos técnicos del dispositivo de referencia
    dispositivo_x = df_temp[df_temp['nombre'].str.lower() == nombre_dispositivo][columnas_tecnicas]

    if dispositivo_x.empty:
        print(f"[bold red]⚠️ Dispositivo '{nombre_dispositivo}' no encontrado o no cumple filtros.[/bold red]")
        return

    dispositivos_solo_datos = df_temp[columnas_tecnicas]
    distancias = euclidean_distances(dispositivo_x, dispositivos_solo_datos)[0]

    # Agregar la distancia al dataframe
    df_temp = df_temp.copy()
    df_temp['distancia'] = distancias

    # Excluir el dispositivo de referencia
    df_temp = df_temp[df_temp['nombre'].str.lower() != nombre_dispositivo]
    df_temp = df_temp.sort_values(by='distancia').head(top_n)

    # Visualización tipo semáforo
    console.print("[bold cyan]🔍 Dispositivos similares a:[/bold cyan]", nombre_dispositivo.upper())
    for idx, row in df_temp.iterrows():
        color = "green" if row["distancia"] <= 0.05 else "yellow" if row["distancia"] <= 0.10 else "red"
        console.print(f"[{color}]🔗 {row['nombre']}[/] - Distancia: {row['distancia']:.4f}")

"""#Paso 5. Recomendador basado en similitud (euclidiana)
Se calculó la distancia euclidiana entre vectores de variables técnicas para encontrar los dispositivos más similares:
Elegiremos un dispositivo de referencia (por ejemplo, uno específico como "Rebar-18").

Extraemos sus características técnicas y se calculara la distancia euclidiana desde ese dispositivo hacia todos los demás.
"""

#Importamos la función que permite calcular distancias euclídeas entre vectores numéricos.
from sklearn.metrics.pairwise import euclidean_distances

# Paso 1: Elegir dispositivo de referencia (nombre debe estar en df_normalizado['nombre'])
dispositivo_referencia = "Rebar-18"

# Paso 2: Extraer el vector del dispositivo de referencia
dispositivo_x = df_normalizado[df_normalizado['nombre'] == dispositivo_referencia]

# Verificamos si el dispositivo existe
if dispositivo_x.empty:
    print(f"Dispositivo '{dispositivo_referencia}' no encontrado.")
else:
    # Paso 3: Remover columna 'nombre' para trabajar solo con variables numéricas
    dispositivos_solo_datos = df_normalizado.drop(columns=['nombre'])

    # Paso 4: Calcular distancias euclidianas
    distancias = euclidean_distances(dispositivo_x.drop(columns=['nombre']), dispositivos_solo_datos)

    # Paso 5: Agregar resultados al DataFrame
    df_resultado = df_normalizado.copy()
    df_resultado['distancia'] = distancias.flatten()

    # Paso 6: Ordenar por menor distancia (más similar primero)
    df_resultado_ordenado = df_resultado.sort_values(by='distancia')

    # Paso 7: Mostrar los 5 más similares (excepto a sí mismo)
    print("Dispositivos más similares a", dispositivo_referencia)
    display(df_resultado_ordenado[df_resultado_ordenado['nombre'] != dispositivo_referencia].head(8))

"""#Paso 6. Función recomendadora con visualización de compatibilidad.

Se desarrolló una función reutilizable en Python que permite ingresar el nombre de un dispositivo neuroendovascular y obtener, como salida, los dispositivos más similares según su distancia euclidiana en un espacio normalizado de características técnicas. Para facilitar la interpretación, se implementó un sistema tipo semáforo de compatibilidad técnica, que clasifica los resultados como “Alta”, “Media” o “Baja” compatibilidad, usando colores verde, naranjo y rojo respectivamente.

Esta clasificación se realiza automáticamente según los cuantiles de la distribución de distancias, de modo que los dispositivos más cercanos al vector de referencia reciban color verde, y los más alejados, color rojo. El resultado se presenta en una tabla HTML interactiva que facilita la exploración visual de alternativas terapéuticas compatibles.
"""

from sklearn.metrics.pairwise import euclidean_distances
from IPython.display import display, HTML

def recomendar_dispositivos(df_normalizado, dispositivo_referencia, columnas_tecnicas, top_n=5):
    # Verificar si el dispositivo existe
    if dispositivo_referencia not in df_normalizado['nombre'].values:
        print(f"Dispositivo '{dispositivo_referencia}' no encontrado.")
        return

    # Extraer el vector del dispositivo de referencia
    dispositivo_x = df_normalizado[df_normalizado['nombre'] == dispositivo_referencia]

    # Calcular distancias euclidianas (excepto columna nombre)
    dispositivos_solo_datos = df_normalizado.drop(columns=['nombre'])
    distancias = euclidean_distances(dispositivo_x.drop(columns=['nombre']), dispositivos_solo_datos)

    # Crear DataFrame con resultados
    df_resultado = df_normalizado.copy()
    df_resultado['distancia'] = distancias.flatten()

    # Calcular cortes de terciles (sin el propio dispositivo)
    distancias_sin_ref = df_resultado[df_resultado['nombre'] != dispositivo_referencia]['distancia']
    corte_verde = distancias_sin_ref.quantile(1/3)
    corte_amarillo = distancias_sin_ref.quantile(2/3)

    # Clasificación tipo semáforo con HTML
    def clasificar_compatibilidad_color(d):
        if d <= corte_verde:
            return '<span style="color: green; font-weight: bold;">Alta</span>'
        elif d <= corte_amarillo:
            return '<span style="color: orange; font-weight: bold;">Media</span>'
        else:
            return '<span style="color: red; font-weight: bold;">Baja</span>'

    df_resultado['compatibilidad'] = df_resultado['distancia'].apply(clasificar_compatibilidad_color)

    # Ordenar por menor distancia
    df_resultado_ordenado = df_resultado.sort_values(by='distancia')

    # Mostrar tabla HTML con colores visibles
    tabla_html = df_resultado_ordenado[df_resultado_ordenado['nombre'] != dispositivo_referencia][
        ['nombre', 'distancia', 'compatibilidad'] + columnas_tecnicas].head(top_n)

    print(f"\nDispositivos más similares a '{dispositivo_referencia}' (según distancia euclidiana):")
    display(HTML(tabla_html.to_html(escape=False, index=False)))

columnas_tecnicas = ['id_mm', 'od_pulgadas', 'od_mm', 'od_fr',
                     'id_pulgadas', 'id_fr', 'longitud_cm']

# Ejecutar recomendación para un dispositivo específico
recomendar_dispositivos(df_normalizado, "Rebar-18", columnas_tecnicas, top_n=30)

"""##Es un gráfico de barras horizontales que representa la distancia euclidiana entre un dispositivo de referencia (rebar-18) y otros dispositivos neuroendovasculares, ordenados de más similares a menos similares."""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial.distance import cdist

# Cargar la base de datos
df = pd.read_csv('base_dispositivos_normalizada 2.0.csv')

# Asegurar que la columna 'nombre' esté en minúscula y sin espacios extra
df['nombre'] = df['nombre'].str.strip().str.lower()

# Seleccionar columnas numéricas para la normalización
columnas_numericas = df.select_dtypes(include=np.number).columns
scaler = MinMaxScaler()
datos_normalizados = scaler.fit_transform(df[columnas_numericas])
df_normalizado = pd.DataFrame(datos_normalizados, columns=columnas_numericas)

# Agregar columna de nombre para referencia
df_normalizado['nombre'] = df['nombre']

# Elegir el dispositivo de referencia
dispositivo_ref = 'rebar-18'

# Verificar si existe en el DataFrame
if dispositivo_ref not in df_normalizado['nombre'].values:
    raise ValueError(f'El dispositivo "{dispositivo_ref}" no está en la base de datos.')

# Obtener vector del dispositivo base
dispositivo_vector = df_normalizado[df_normalizado['nombre'] == dispositivo_ref][columnas_numericas].values

# Calcular distancias euclidianas
distancias = cdist(df_normalizado[columnas_numericas], dispositivo_vector, metric='euclidean').flatten()
df_normalizado['distancia'] = distancias

# Excluir el propio dispositivo
df_resultados = df_normalizado[df_normalizado['nombre'] != dispositivo_ref]

# Obtener los 10 más similares
top_10 = df_resultados.sort_values(by='distancia').head(10).copy()

# Asignar colores tipo semáforo según cuartiles
cuartiles = np.quantile(top_10['distancia'], [0.33, 0.66])
def asignar_color(dist):
    if dist <= cuartiles[0]:
        return 'green'
    elif dist <= cuartiles[1]:
        return 'gold'
    else:
        return 'red'
top_10['color'] = top_10['distancia'].apply(asignar_color)

# Graficar
plt.figure(figsize=(10, 6))
bars = plt.barh(top_10['nombre'], top_10['distancia'], color=top_10['color'])
plt.xlabel('Distancia Euclidiana')
plt.title(f'Dispositivos más similares a: {dispositivo_ref}')
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""###*¿Qué interpretamos del gráfico?*

Vasco+18 es el dispositivo más similar a Rebar-18 (distancia muy baja, color verde).

Progreat 2.7 y Gama17 también son bastante compatibles (verde).

Via 17, Eclipse 2L, Excelsior SL-10 se ubican en un nivel medio de similitud (amarillo).

XT-17, Marathon, Apollo, y Echelon 10 son los menos compatibles con rebar-18 (rojo), es decir, tienen diferencias más grandes en sus características técnicas.

##6.1 Función Predictiva de Recomendación Basada en Distancia Euclidiana

El propósito de esta función es entregar una recomendación de los dispositivos más próximos técnicamente a uno elegido, considerando dimensiones como diámetros internos y externos (en mm y pulgadas), longitud, y compatibilidad. Esta aproximación permite fortalecer la toma de decisiones clínicas cuando se requiere reemplazar o buscar equivalencias a un determinado dispositivo.
"""

from sklearn.metrics.pairwise import euclidean_distances
from IPython.display import display, HTML

def mostrar_similares(dispositivo_referencia, df_base=df_normalizado, top_n=5):
    # Paso 1: Verificamos que el dispositivo exista
    if dispositivo_referencia not in df_base['nombre'].values:
        print(f"Dispositivo '{dispositivo_referencia}' no encontrado.")
        return

    # Paso 2: Separar datos técnicos y vector del dispositivo de referencia
    columnas_tecnicas = ['id_mm', 'od_pulgadas', 'od_mm', 'od_fr',
                         'id_pulgadas', 'id_fr', 'longitud_cm']
    dispositivo_x = df_base[df_base['nombre'] == dispositivo_referencia]
    dispositivos_solo_datos = df_base.drop(columns=['nombre'])

    # Paso 3: Calcular distancias euclidianas
    distancias = euclidean_distances(dispositivo_x.drop(columns=['nombre']),
                                     dispositivos_solo_datos)

    # Paso 4: Guardar resultados
    df_resultado = df_base.copy()
    df_resultado['distancia'] = distancias.flatten()

    # Paso 5: Clasificar compatibilidad (semáforo por terciles)
    corte_verde = df_resultado['distancia'].quantile(1/3)
    corte_amarillo = df_resultado['distancia'].quantile(2/3)

    def clasificar_color(d): #Divide las distancias en terciles (bajo, medio, alto).
        if d <= corte_verde:
            return '<span style="color: green; font-weight: bold;">Alta</span>'
        elif d <= corte_amarillo:
            return '<span style="color: orange; font-weight: bold;">Media</span>'
        else:
            return '<span style="color: red; font-weight: bold;">Baja</span>'

    df_resultado['compatibilidad'] = df_resultado['distancia'].apply(clasificar_color)

    # Paso 6: Ordenar resultados y filtrar
    df_resultado_ordenado = df_resultado.sort_values(by='distancia')
    df_final = df_resultado_ordenado[df_resultado_ordenado['nombre'] != dispositivo_referencia]

    # Paso 7: Mostrar top N en formato HTML
    tabla_html = df_final[['nombre', 'distancia', 'compatibilidad']].head(top_n).to_html(escape=False, index=False)
    display(HTML(f"<h4>Dispositivos más similares a <b>{dispositivo_referencia}</b>:</h4>"))
    display(HTML(tabla_html))

# Mostrar los dispositivos más parecidos al 'vasco+ 18'
mostrar_similares('rebar-18')

"""# Conclusion de Utilidad y valor agregado.

###-La función es reutilizable y acepta como entrada cualquier nombre de dispositivo presente en la base.

###-Brinda una herramienta rápida y visual de recomendación basada en similitud técnica.

###-Facilita la toma de decisiones clínicas con un criterio cuantitativo. Brindando una recomendación objetiva y medible, basada en similitud matemática y no solo en experiencia clínica.

###-El uso de colores tipo “semáforo” facilita la interpretación inmediata para médicos, técnicos e ingenieros clínicos.
"""